### PR TITLE
Rest of homepage

### PR DESCRIPTION
**Pull request by iteles**
This PR creates the rest of the homepage with preliminary (english) content, including:
+ Adding a section on travel https://github.com/nelsonic/perfect-day/issues/28
+ Adding a section on gift registry https://github.com/nelsonic/perfect-day/issues/29
+ Some general bug fixing and tweaks to padding https://github.com/nelsonic/perfect-day/issues/31

### CODE REVIEW

**Comment by nelsonic** [comment]
@iteles there doesn't _appear_ to be a "We Need Phoenix for ..." _usecase_ in this project.
Is there anything you _need_ me for here?

**Comment by iteles** [comment]
No, thanks for setting me straight, just review and merging of the HTML please @nelsonic.

**Comment by nelsonic** [comment]
@iteles it would be cool if you could make a few notes in here: https://github.com/dwyl/learn-github-pages

**Review by nelsonic — APPROVED** [review]
@iteles HTML, Layout and Styling looks good. 
Not a fan of the "Army Green" or the _gigantic_ "l" in my name due to the choice of font ... but looks good. thanks. 👍 
image

**Pull request merged**
